# Generated by Django 3.2.8 on 2022-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_foodrecipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='category',
            field=models.CharField(choices=[('VR', 'Vegetarian recipes'), ('NVR', 'NonVegetarian recipes'), ('O', 'Other')], max_length=22),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipeimg'),
        ),
    ]
