# Generated by Django 3.2.8 on 2022-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220617_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='recipe_image',
            field=models.ImageField(default=23, upload_to='recipeimg'),
            preserve_default=False,
        ),
    ]
